### ISSUE TITLE
message edit/deletion counts

### ISSUE THREAD

**Issue by a-lexer** [olliequ/KittyBot#29]
i.e. so we can rank people based on how many messages they sneakily delete, possibly with deleterious social results.

would be nice! Possible?

**Comment by olliequ** [comment]
It should be possible using the [GuildMessageDeleteEvent](https://www.hikari-py.dev/hikari/events/message_events.html#hikari.events.message_events.GuildMessageDeleteEvent).

Sounds like a good idea :)

You could create a new table with `userid` and `delete_count` fields, and call that table (sort by descend) to get the output. Form an embed from that.

**Comment by olliequ** [comment]
Just implemented with bcc86a8aea837e86afa2a2a21d90c161c1118a84 ;)

**Comment by olliequ** [comment]
Turns out my implementation (the `deletesinquiry` feature) is currently incorrect as it increments a user's count even if someone **else** deletes their message. It works fine if everyone just deletes their own messages, but that obviously doesn't happen all the time. I'll edit this comment if/when I delete it.

The problem: You can't identify *who* deleted a message within `GuildMessageDeleteEvent`. Only the author of the message. There *is* a way to check audit logs with hikari (so you can see who the deleter is), however it's apparently only available using some cursed method using this: https://www.hikari-py.dev/hikari/api/rest#hikari.api.rest.RESTClient.fetch_audit_log

And even then audit logs do not create an event for people who delete their own messages. Audit logs only show message deletes when someone deletes **someone else's** message. So you'd have to use this audit logs method in combination with a method identifying when a user deletes their own message (possible with `GuildMessageDeleteEvent` -- you could cross-check it with the audit log check).

---------

So, it's currently still available as a command, but I might remove it. I'm not reopening this issue as it seems based on the above this feature is not easy to make (idek if it's possible -- if you find a way do say!). I wanted to add these comments here as I put them in a different issue by mistake.
